version: '3.8'

services:
  pinepaste.api:
    build:
      context: ../
      dockerfile: ./src/PinePaste.Api/Dockerfile
    ports:
      - "4022:4022"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
