name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List directory contents
      run: ls -R

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore PinePaste.sln
      working-directory: ./pinepaste

    - name: Build the project
      run: dotnet build PinePaste.sln --configuration Release
      working-directory: ./pinepaste
